# Formel 1 datasett

Denne oppgaven leker seg litt med ett data sett fra F1.

Oppgaven bruker ulike funksjoner som vi har sett på i kurset.

### Oppgave 0

Laste ned datasettet fra lenken:

http://ergast.com/mrd/db/

under der hvor det står "CSV Data tables". Legg filen i samme mappe som notebooken og pakk den ut.

### Oppgave 1
Last inn pakkene pandas og numpy.

Last deretter inn de tre regnearkene "races.csv", "lap_times.csv" og "drivers.csv".

In [1]:
import pandas as pd
import numpy as np

races = pd.read_csv("F1data/races.csv")
laps = pd.read_csv("F1data/lap_times.csv")
drivers = pd.read_csv("F1data/drivers.csv")

### Oppgave 2
Bruk .info(), .head() og .describe() på regnearkene og utforsk hva de inneholder.

In [45]:
drivers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 853 entries, 0 to 852
Data columns (total 9 columns):
driverId       853 non-null int64
driverRef      853 non-null object
number         853 non-null object
code           853 non-null object
forename       853 non-null object
surname        853 non-null object
dob            853 non-null datetime64[ns]
nationality    853 non-null object
url            853 non-null object
dtypes: datetime64[ns](1), int64(1), object(7)
memory usage: 60.1+ KB

### Oppgave 3
Vi kan begynne med å se på noen av sjåførene i Formel 1. 

Finn sjåføren med koden "TSU".

In [92]:
drivers[drivers["code"]=="TSU"]

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
850,852,tsunoda,22,TSU,Yuki,Tsunoda,2000-05-11,Japanese,http://en.wikipedia.org/wiki/Yuki_Tsunoda

### Oppgave 4
Når er han født?

In [6]:
drivers[drivers["code"]=="TSU"]["dob"]

850    2000-05-11
Name: dob, dtype: object

### Oppgave 5
Er det noen sjåfører som er født på samme dag som deg?

In [104]:
drivers[drivers["dob"]=="1999-02-28"]

Empty DataFrame
Columns: [driverId, driverRef, number, code, forename, surname, dob, nationality, url]
Index: []

### Oppgave 6
Biblioteket datetime i python kan håndtere datoer og klokkeslett på en god måte.

"pd.to_datetime"-funksjonen konverterer kolonnen "dob", slik at den blir forstått som datoer.

"min_bursdag" er en variabel som forståes av datetime-biblioteket som en dato. Vi kan derfor enkelt finne ut for eksempel hvilken av sjåførene som er født nærmest bursdagen din, ved å treffe fra kolonnen med datoer for sjåførenes bursdager med din.

Legg fullfør kodecellen og svar på spørsmålet: 

Hvilken sjåfør er født nærmest deg i tid?

### Bonus:

Vi kan også se om en dato kom før en annen ved hjelp av "<" og ">"-operatorene. 

Da vil datoer for eksempel datoen: 2020.04.19 > 2019.04.19 = True

Hvem av sjåførene er født etter deg?

In [25]:
import datetime
drivers["dob"] = pd.to_datetime(drivers["dob"])
år = 1999
måned = 2
dag = 28
min_bursdag = datetime.datetime(år,måned,dag)
drivers["dob"] - min_bursdag

0     -5165 days
1     -7964 days
2     -4994 days
3     -6423 days
4     -6341 days
         ...
848    -978 days
849   -1254 days
850     438 days
851       2 days
852      22 days
Name: dob, Length: 853, dtype: timedelta64[ns]

### Oppgave 7

Ved hjelp av "groupby"-funksjonen kan vi gruppere regnearket vårt etter en egenskap. 

Se på kolonnene vi har i regnearket, hvilke av disse gir det mening å gruppere sjåførene etter?

Hvor mange sjåfører i Formel 1 kommer fra Finland?

In [43]:
drivers.groupby("nationality").get_group("British")

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
13,14,coulthard,\N,COU,David,Coulthard,1971-03-27,British,http://en.wikipedia.org/wiki/David_Coulthard
17,18,button,22,BUT,Jenson,Button,1980-01-19,British,http://en.wikipedia.org/wiki/Jenson_Button
18,19,davidson,\N,DAV,Anthony,Davidson,1979-04-18,British,http://en.wikipedia.org/wiki/Anthony_Davidson
50,51,wilson,\N,\N,Justin,Wilson,1978-07-31,British,http://en.wikipedia.org/wiki/Justin_Wilson_(ra...
...,...,...,...,...,...,...,...,...,...
828,829,stevens,28,STE,Will,Stevens,1991-06-28,British,http://en.wikipedia.org/wiki/Will_Stevens
834,835,jolyon_palmer,30,PAL,Jolyon,Palmer,1991-01-20,British,http://en.wikipedia.org/wiki/Jolyon_Palmer
844,846,norris,4,NOR,Lando,Norris,1999-11-13,British,http://en.wikipedia.org/wiki/Lando_Norris
845,847,russell,63,RUS,George,Russell,1998-02-15,British,http://en.wikipedia.org/wiki/George_Russell_%2...
849,851,aitken,89,AIT,Jack,Aitken,1995-09-23,British,http://en.wikipedia.org/wiki/Jack_Aitken

### Oppgave 8
La oss se litt på løpene i F1.

Finn hvilket løp som ligger på indeks 0 i regnearket "races".

In [47]:
races.iloc[0]

raceId                                                       1
year                                                      2009
round                                                        1
circuitId                                                    1
name                                     Australian Grand Prix
date                                                2009-03-29
time                                                  06:00:00
url          http://en.wikipedia.org/wiki/2009_Australian_G...
Name: 0, dtype: object

### Oppgave 9

Hva er de 25 siste løpene i regnearket?

In [48]:
races.iloc[-25:-1]

,raceId,year,round,circuitId,name,date,time,url
1033,1046,2020,16,3,Sakhir Grand Prix,2020-12-06,17:10:00,https://en.wikipedia.org/wiki/2020_Sakhir_Gran...
1034,1047,2020,17,24,Abu Dhabi Grand Prix,2020-12-13,13:10:00,https://en.wikipedia.org/wiki/2020_Abu_Dhabi_G...
1035,1053,2021,2,21,Emilia Romagna Grand Prix,2021-04-18,13:00:00,http://en.wikipedia.org/wiki/2021_Emilia_Romag...
1036,1052,2021,1,3,Bahrain Grand Prix,2021-03-28,15:00:00,https://en.wikipedia.org/wiki/2021_Bahrain_Gra...
1037,1051,2021,21,1,Australian Grand Prix,2021-11-21,06:00:00,http://en.wikipedia.org/wiki/2021_Australian_G...
1038,1054,2021,3,75,Portuguese Grand Prix,2021-05-02,13:00:00,http://en.wikipedia.org/wiki/2021_Portuguese_G...
1039,1055,2021,4,4,Spanish Grand Prix,2021-05-09,13:00:00,http://en.wikipedia.org/wiki/2021_Spanish_Gran...
1040,1056,2021,5,6,Monaco Grand Prix,2021-05-23,13:00:00,http://en.wikipedia.org/wiki/2021_Monaco_Grand...
1041,1057,2021,6,73,Azerbaijan Grand Prix,2021-06-06,12:00:00,http://en.wikipedia.org/wiki/2021_Azerbaijan_G...
1042,1058,2021,7,7,Canadian Grand Prix,2021-06-13,18:00:00,http://en.wikipedia.org/wiki/2021_Canadian_Gra...
1043,1059,2021,8,34,French Grand Prix,2021-06-27,13:00:00,http://en.wikipedia.org/wiki/2021_French_Grand...
1044,1060,2021,9,70,Austrian Grand Prix,2021-07-04,13:00:00,http://en.wikipedia.org/wiki/2021_Austrian_Gra...
1045,1061,2021,10,9,British Grand Prix,2021-07-18,14:00:00,http://en.wikipedia.org/wiki/2021_British_Gran...
1046,1062,2021,11,11,Hungarian Grand Prix,2021-08-01,13:00:00,http://en.wikipedia.org/wiki/2021_Hungarian_Gr...
1047,1063,2021,12,13,Belgian Grand Prix,2021-08-29,13:00:00,http://en.wikipedia.org/wiki/2021_Belgian_Gran...
1048,1064,2021,13,39,Dutch Grand Prix,2021-09-05,13:00:00,http://en.wikipedia.org/wiki/2021_Dutch_Grand_...
1049,1065,2021,14,14,Italian Grand Prix,2021-09-12,13:00:00,http://en.wikipedia.org/wiki/2021_Italiian_Gra...
1050,1066,2021,15,71,Russian Grand Prix,2021-09-26,12:00:00,http://en.wikipedia.org/wiki/2021_Russian_Gran...
1051,1067,2021,16,15,Singapore Grand Prix,2021-10-03,12:00:00,http://en.wikipedia.org/wiki/2021_Singapore_Gr...
1052,1068,2021,17,22,Japanese Grand Prix,2021-10-10,05:00:00,http://en.wikipedia.org/wiki/2021_Japanese_Gra...
1053,1069,2021,18,69,United States Grand Prix,2021-10-24,19:00:00,http://en.wikipedia.org/wiki/2021_United_State...
1054,1070,2021,19,32,Mexico City Grand Prix,2021-10-31,19:00:00,http://en.wikipedia.org/wiki/2021_Mexican_Gran...
1055,1071,2021,20,18,Brazilian Grand Prix,2021-11-07,17:00:00,http://en.wikipedia.org/wiki/2021_Brazilian_Gr...
1056,1072,2021,22,77,Saudi Arabian Grand Prix,2021-12-05,16:00:00,http://en.wikipedia.org/wiki/2021_Saudi_Arabia...

### Oppgave 10

Hvor mange løp var det i 2017?

In [54]:
races[races["year"]==2017].count()

raceId       20
year         20
round        20
circuitId    20
name         20
date         20
time         20
url          20
dtype: int64

### Oppgave 11

Finn ut hvor mange løp det var i hvert år.

Svar på noen av spørsmålene:
Hvilket år var det flest løp?
Hvilket var det minst?
Nest mest?

Lag gjerne en oversikt sortert i stigende rekkefølge.

In [58]:
races.groupby("year").count().sort_values("name")

      raceId  round  circuitId  name  date  time  url
year
1950       7      7          7     7     7     7    7
1955       7      7          7     7     7     7    7
1951       8      8          8     8     8     8    8
1952       8      8          8     8     8     8    8
1961       8      8          8     8     8     8    8
...      ...    ...        ...   ...   ...   ...  ...
2012      20     20         20    20    20    20   20
2016      21     21         21    21    21    21   21
2018      21     21         21    21    21    21   21
2019      21     21         21    21    21    21   21
2021      23     23         23    23    23    23   23

[72 rows x 7 columns]

### Oppgave 12
De tre regnearkene har noe til felles slik at vi kan koordinere data på tvers av dem.
I "laps" har vi både kolonnene "raceId" og "driverId" for å betegne hvilket løp og hvilken sjåfør som kjørte runden.

Vi ønsker å plukke ut alle rundene fra Bahrain Grand Prix i 2021. Fra "races"-regnearket, finn hvilken raceId det løpet har.

In [63]:
raceid = races[(races["name"]=="Bahrain Grand Prix") & (races["year"]==2021)]["raceId"]

1036    1052
Name: raceId, dtype: int64

Vi kan nå plukke ut alle rundene fra laps med raceId = 1052, som vi fant i forrige oppgave, lagre de i et nytt regneark, ved hjelp av groupby og get_group funskjonene.

In [66]:
bahrain_laps = laps.groupby("raceId").get_group(1052)

### Oppgave 13
Fra regnearket med alle rundene i, svar på følgende spørsmål.

Hvor mange runder hadde løpet?

Hvem vant? Slå opp "driverId"-verdien i "drivers"-regnearket.

Hvem var i snitt på høyest posisjon?

Hvor kort var den raskeste runden under løpet?

Hva var den gjennomsnittlige rundetiden?

Basert på den gjennomsnittlige rundetiden og det faktum at en runde er 5412 m, hva var hastigheten i km/t?

### Oppgave 14

Lag en funksjon som regner millisekunder om til sekunder.

In [76]:
def millisekunder_til_sekunder(ms):
    return ms/1000

### Oppgave 15
Lag en ny kolonne til rundene i Bahrain som heter "seconds". Bruk funksjonen fra forrige oppgave til å fylle inn verdiene.

In [75]:
bahrain_laps["seconds"] = millisekunder_til_sekunder(bahrain_laps["milliseconds"])

/home/johan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.